# ===========
# Date: 2026-05-05 14:23
# Author: Vulcan
# LastEditTime: 2026-05-13 01:36
# Description: PPO训练的自动化配置文件，定义了训练框架、任务、环境数量、迭代次数等关键参数，以及Isaac Lab的渲染设置和Checkpoint的存储路径与续训选项。
# ==========
training:
    framework: "skrl"
    task: "Template-Pipe-Robot-Lab-v1"
    num_envs: 32
    max_iterations_per_round: 300
    total_rounds: 180
    env_pipe_id_range: [91, 170]

isaaclab:
    headless: true
    video: false
    video_interval: 2000

checkpointing:
    log_root_dir: "logs/skrl/ppo_auto_04"  # Tensorboard 日志与 Checkpoint 存放的根目录
    resume_from_latest: true              # 若开启，自动扫描 `log_root_dir` 下最新修改的 `.pt` 权重文件进行断点续训接力
    saves_per_round: 2                    # 每小轮训练保存模型的次数 (例如配为2, 则在小轮中间和结束各保存一次)
    keep_max_pt_files: 4                  # 硬盘清理：将所有训练合并为单一连续任务后，文件夹内仅保留最新的前 5 个 `.pt` 权重文件，其余旧权重自动删除以节约开销(不会删除best_agent)