# ===========
# Date: 2026-02-21 08:58
# Author: Vulcan
# LastEditTime: 2026-05-04 23:09
# Description: 用于配置管路生成器工作时的可选参数
# ==========
generation:
    mode: "random"  # random: 每次调用生成器都会生成一个完全随机的管道环境
                    # fixed:  按照定义的信息列表生成管道环境，适用于测试和调试
    fixed_info: [   # 仅当fixed模式下生效，【管道类型， 直径， 长度(转弯半径), 前置偏转，后置偏转(deg)】
        [0 , 0.36 , 1.5 , 0 , 0],
        [1 , 0.36 , 0.3 , 90 , 90],
        [0 , 0.36 , 1.5 , 0 , 0],
    ]
    second_mode: "safe"     # random: 管道直径完全随机
                            # safe: 限定弯管前后必须为直管，且弯管的直径必须等于前后直管的直径
    # * 输出保存路径
    total_nums: 100 # 一次运行生成器批量生成的管道环境数目
    meshes_path: "./meshes" # 存放管道网格的相对路径
    usd_path: "./usd" # 存放管道环境的USD文件的相对路径
    json_path: "./json" # 存放管道参数以及变换矩阵的json文件的相对路径

pipe:
    # 通用参数
    num_pipe_prims: [1 , 1] # 管道原件数目(直管&弯管)，生成器中随机取一个整数
    D_range: [0.25 , 0.40]  # 管道直径范围, m

    # 直管适用
    L_range_straight: [0.5 , 1.5]  # 直管长度范围, m
    D_change_prob: 0.5 # 生成管道原件时，生成直管时改变直径的概率

    # 弯管适用， 由于弯管需要使用STL生成网格，为减小数据量，弯管的信息采用基于给定步长取整段的方式，
    # 便于复用已经生成过的弯管网格
    L_range_bend: [0.3 , 0.5] # 生成的弯管的转弯半径，m
    angle_range_bend: [45 , 90] # 生成的弯管的转弯角度范围，deg
    D_step_bend: 0.05 # 生成弯管时，直径取值的步长，m
    L_step_bend: 0.1 # 生成弯管时，转弯半径取值的步长，m
    angle_step_bend: 10 # 生成弯管时，转弯角度取值的步长，deg
    probability_bend: 0.6 # 生成管道原件时，生成弯管的概率

physics:
    # 物理材质属性
    static_friction_range: [0.8 , 1.0] # 静摩擦系数范围
    dynamic_friction_range: [0.8 , 1.0] # 动摩擦系数范围
    restitution_range: [0.0 , 0.0] # 恢复系数范围



